# Generated by Django 5.2.4 on 2025-09-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sintoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comun', models.CharField(max_length=100)),
                ('nombre_cientifico', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
                ('propiedades', models.TextField(help_text='Describe las propiedades medicinales.')),
                ('sintomas_tratados', models.ManyToManyField(related_name='plantas_recomendadas', to='plantas.sintoma')),
            ],
        ),
    ]
