# Generated by Django 5.2.4 on 2025-09-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planta',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='planta',
            name='propiedades',
        ),
        migrations.AddField(
            model_name='planta',
            name='advertencias',
            field=models.TextField(blank=True, help_text="Contraindicaciones importantes, como 'No usar durante el embarazo o lactancia'.", null=True),
        ),
        migrations.AddField(
            model_name='planta',
            name='definicion',
            field=models.TextField(blank=True, help_text="Corresponde a la sección 'DEFINICIÓN' de tu archivo.", null=True),
        ),
        migrations.AddField(
            model_name='planta',
            name='fuentes',
            field=models.TextField(blank=True, help_text='Pega aquí los links a estudios o fuentes de información.', null=True),
        ),
        migrations.AddField(
            model_name='planta',
            name='historia',
            field=models.TextField(blank=True, help_text="Corresponde a la sección 'HISTORIA' de la planta.", null=True),
        ),
        migrations.AddField(
            model_name='planta',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Sube una imagen de la planta.', null=True, upload_to='plantas_imagenes/'),
        ),
        migrations.AddField(
            model_name='planta',
            name='usos',
            field=models.TextField(blank=True, help_text="Corresponde a la sección 'USOS', describe cómo aplicar la planta.", null=True),
        ),
        migrations.AddField(
            model_name='sintoma',
            name='recomendaciones',
            field=models.TextField(blank=True, help_text="Advertencias o recomendaciones para tratar este síntoma, como 'Usar solo en casos leves'.", null=True),
        ),
        migrations.AlterField(
            model_name='planta',
            name='nombre_cientifico',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sintoma',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción general del síntoma.', null=True),
        ),
    ]
